# Should be run on compute nodes you want to run jupyter notebook on
# See https://osc.github.io/ood-documentation/latest/app-development/tutorials-interactive-apps/add-jupyter/software-requirements.html
# - Will already have openssl and lmod

- name: Ensure python3.9 installed
  dnf:
    name: python39
  tags: install

- name: Install jupyter venv
  # Requires separate step so that the upgraded pip is used to install packages
  pip:
    name: pip
    state: latest
    virtualenv: /opt/jupyter-py39
    virtualenv_command: python3.9 -m venv
  tags: install

- name: Copy jupyter requirements file
  copy:
    src: jupyter_requirements.txt
    dest: /opt/jupyter-py39/jupyter_requirements.txt
  tags: install

- name: Install jupyter package in venv
  pip:
    virtualenv: /opt/jupyter-py39
    virtualenv_command: python3.9 -m venv
    requirements: /opt/jupyter-py39/jupyter_requirements.txt
  tags: install


