# Should be run on compute nodes you want to run the graphical desktop on
- name: Enable TurboVNC repo
  tags: install
  get_url:
    url: https://raw.githubusercontent.com/TurboVNC/repo/main/TurboVNC.repo
    dest: /etc/yum.repos.d/TurboVNC.repo

- name: Install EPEL
  tags: install
  yum:
    name: epel-release

- name: Install VNC-related packages
  tags: install
  dnf:
    name:
      - turbovnc-3.0.1
      - nmap-ncat
      - python3.9

- name: Install Xfce desktop
  tags: install
  yum:
    name: '@Xfce'
  
# - name: Ensure python3.9 installed
#   dnf:
#     name: python39
#   tags: install

- name: Install websockify venv
  # Requires separate step so that the upgraded pip is used to install packages
  pip:
    name: pip
    state: latest
    virtualenv: /opt/websockify-py39
    virtualenv_command: python3.9 -m venv
  tags: install

- name: Install websockify package in venv
  pip:
    name: websockify
    virtualenv: /opt/websockify-py39
    virtualenv_command: python3 -m venv
  tags: install

- name: Symlink websockify to where Open Ondemand expects
  file: "{{ item }}"
  loop:
    - path: /opt/websockify
      state: directory
    - src: /opt/websockify-py39/bin/websockify
      dest: /opt/websockify/run
      state: link
- name: Disable screensaver # as users might not have passwords
  yum:
    name: xfce4-screensaver
    state: absent
  when: not (openondemand_desktop_screensaver | bool)
