---

- name: "Do the preliminary node setups"
  hosts: all
  tags: pre_tasks_all
  become: true
  tasks:
    - include_role:
        name: vshpc.prov.pre-tasks

# TODO: KBENDL - check compatibility with new playbook
- name: "NREL pre - Mount cephfs volumes"
  hosts: all
  tags:
    - vs_pre
    - aco.core.cephfs
  become: true
  tasks:
    - include_role:
        name: aco.core.cephfs
      tags:
        - aco.core.cephfs

    # - name: Set timezone to Americas/Denver
    #   timezone:
    #     name: America/Denver
    #   tags:
    #     - pre_set_time_on_servers

    # - include_role:
    #     name: aco.core.ntp
    #   tags:
    #     - pre_set_time_on_servers

# - name: "NREL PRE - dnf packages"
#   hosts: all
#   tags: dnf_initial_update
#   become: true
#   tasks:
#     - lineinfile:
#         path: /etc/yum.repos.d/cuda-rhel8.repo
#         regexp: '^enabled'
#         line: enabled=0

#     - name: dnf fix challenging dependency issues
#       dnf:
#         name: "*"
#         nobest: true
#         allowerasing: true
#         skip_broken: true

# - name: "NREL pre - set cluster root password"
#   hosts: all
#   tags: root_pass_cli
#   become: true
#   tasks:
#     - name: include root if called
#       include_role:
#         name: root_pass_cli
#       when: new_root_pass is defined

# - name: "NREL pre - set admin hostnames to hpc.nrel.gov domain"
#   hosts: control,login
#   tags: set_hpc_hostname
#   become: true
#   tasks:
#     - shell: "hostnamectl set-hostname {{ ansible_hostname }}.hpc.nrel.gov"

# This may be fixed now
# # ref: Error: cannot setup namespace using "/usr/bin/newuidmap": should have setuid or have filecaps setuid:
# - name: "podman uid-gid workaround"
#   hosts:
#     - cluster
#   become: true
#   tags:
#     - vs_pre
#     - uid_gid_hack
#   tasks:
#     - name: "set newuidmap/newgidmap perms so containers will start"
#       file:
#         path: "{{ item }}"
#         mode: '4755'
#       loop:
#         - /usr/bin/newgidmap
#         - /usr/bin/newuidmap

# TODO - get latest playbook
# - name: Ensure yum repos are local
#   hosts: all
#   tags: ansible_yum_config
#   become: true
#   tasks:
#     - include_role:
#         name: ansible_yum_config
# git@github.nrel.gov:acoinf/vshpc.prov.pre-tasks.git
