---
roles:
  - src: stackhpc.nfs
  - src: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: https://github.com/stackhpc/ansible_role_spack
    name: stackhpc.spack
    version: HEAD
  - src: jriguera.configdrive

collections:
- name: containers.podman
- name: community.grafana
- name: community.general
- name: ansible.posix
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: main
...
