---
# See: https://opensearch.org/docs/latest/security-plugin/configuration/index/

# Path to template that specifies opensearch users
opensearch_internal_users_path: "{{ appliances_repository_root }}/environments/common/files/opensearch/internal_users.yml.j2"

# define an idempotent bcrypt hash for the above (requires a 128bit salt in base64 encoding):
opensearch_admin_password_salt: "{{ (2 | pow(128) | int) | random(seed=inventory_hostname) | b64encode }}"
opensearch_admin_password_hash: "{{ vault_elasticsearch_admin_password | password_hash('bcrypt', opensearch_admin_password_salt[0:22]) }}"

# user running the opensearch container
opensearch_podman_user: podman

# Path to host directories
opensearch_config_path: "{{ appliances_state_dir | default('/usr/share') }}/opensearch/config"
opensearch_data_path: "{{ appliances_state_dir | default('/usr/share') }}/opensearch/data"
