cluster_deploy_ssh_keys_extra: []

# List of hw_scsi_models that result in block devices presenting as /dev/sdX
# rather than /dev/vdX
scsi_models:
  # Ceph [https://docs.ceph.com/en/quincy/rbd/rbd-openstack/#image-properties]
  - virtio-scsi
