- name: NREL lab fixes - For compute nodes
  hosts: compute
  become: true
  gather_facts: false
  tasks:
    - name: Create scratch directory - on local SSD on prod
      file:
        path: /var/scratch
        state: directory
