---
# Default to 10GB
cvmfs_quota_limit_mb: 10000

cvmfs_config_default:
  CVMFS_CLIENT_PROFILE: single
  CVMFS_QUOTA_LIMIT: "{{ cvmfs_quota_limit_mb }}"

cvmfs_config_overrides: {}

cvmfs_config: "{{ cvmfs_config_default | combine(cvmfs_config_overrides) }}"
