#openhpc_rebuild_clouds: "/home/rocky/nrel-openrc.sh" # TODO: not sure this will work
openhpc_rebuild_clouds: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/rebuild/clouds.yaml"

openhpc_packages_extra: "{{ openhpc_packages_extra_nrel}}"

openhpc_slurm_partitions:
  - name: "sm"
    default: YES
    maxtime: "4-0" # 1 days 0 hours
  - name: "gpu"
    default: NO
    maxtime: "4-0" # 1 days 0 hours
  - name: "lg"
    default: NO
    maxtime: "4-0" # 1 days 0 hours
  # - name: "gpu8a100"
  #   default: NO
  #   maxtime: "4-0" # 1 days 0 hours
  # - name: "gpu4a100"
  #   default: NO
  #   maxtime: "4-0" # 1 days 0 hours
  # - name: "std"
  #   default: YES
  #   maxtime: "1-0" # 1 days 0 hours
  # - name: "t"
  #   default: NO
  #   maxtime: "4:0:0" # 4 hour 0m 0s
