- hosts: basic_users:!builder
  become: yes
  tags:
    - basic_users
    - users
  gather_facts: yes
  tasks:
    - import_role:
        name: basic_users

- name: Setup EESSI
  hosts: eessi
  tags: eessi
  become: true
  gather_facts: false
  tasks:
    - name: Install and configure EESSI
      import_role:
        name: eessi

- name: Setup CUDA
  hosts: cuda
  become: yes
  gather_facts: no
  tags: cuda
  tasks:
    - import_role:
        name: cuda
