---


nfs_configurations:
  - comment: Home directories served from slurm control node
    nfs_enable:
      server:  "{{ inventory_hostname == groups['control'] | first}}"
      # Don't mount share on server where it is exported from ...
      clients: "{{ inventory_hostname in groups['cluster'] and inventory_hostname not in groups['control'] }}"
    nfs_server: "{{ nfs_server_default }}"
    nfs_export: "/home"
    nfs_client_mnt_point: "/home"

