---
- name: Restart slurm exporter
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-slurm-exporter
    state: restarted
  when:
    - not ansible_check_mode
    - slurm_exporter_state != 'stopped'
