- name: Validate suitability
  include_tasks: validate.yml
  when: _cve_2023_41814_installed_pkgs is undefined

- name: Identify packages to update
  set_fact:
    _cve_2023_41814_updates: "{{ _cve_2023_41814_updates + [item] }}"
  loop: "{{ cve_2023_41914_rpms }}"
  when:
    - item in ansible_facts.packages
    - cve_2023_41914_rpm_fix_ver is version(ansible_facts.packages[item][0].version, '>')

- name: Write packages to be modified to a file
  # allows recovery from failures in subsequent package deletion/rpm install
  copy:
    dest:  "{{ cve_2023_41914_pkglist_path }}"
    content: "{{ _cve_2023_41814_updates | to_nice_yaml }}"
  when: _cve_2023_41814_updates | length > 0
  delegate_to: localhost

- name: Read packages to modify
  set_fact:
    _cve_2023_41814_updates: "{{ lookup('file', cve_2023_41914_pkglist_path) | from_yaml }}"

- name: Identify architecture
  setup:
    gather_subset: architecture

- name: Remove installed packages
  dnf:
    name: "{{ _cve_2023_41814_updates }}"
    state: absent

- name: Install rpms
  dnf:
    name: "{{ cve_2023_41914_rpm_url }}/{{ item }}-{{ cve_2023_41914_rpm_fix_ver }}-{{ cve_2023_41914_rpm_fix_release }}.{{ ansible_architecture }}.rpm"
  loop: "{{ _cve_2023_41814_updates }}"
  register: _cve_2023_41814_rpm_installs

- name: Reload systemd units
  command: systemctl daemon-reload
  when: _cve_2023_41814_rpm_installs.changed
