- name: Start slurmdbd
  systemd:
    name: slurmdbd
    state: started
  # NB: this approach is only suitable for minor version upgrades
  # major ones may timeout on service start due to db upgrades
  when: openhpc_enable.database | default('false') | bool

- name: Start slurmctld
  systemd:
    name: slurmctld
    state: started
  when: openhpc_enable.control | default('false') | bool

- name: Start slurmd
  systemd:
    name: slurmd
    state: started
  when: openhpc_enable.batch | default('false') | bool or 'login' in group_names
