- name: Get package facts
  package_facts:

- name: Set fact for installed Slurm packages
  # this is a subset (same format) as ansible_facts.packages
  set_fact:
    _cve_2023_41814_installed_pkgs: "{{ ansible_facts.packages | dict2items | selectattr('key', 'match', 'slurm-') | items2dict }}"

- name: Ensure only a single version of all slurm-* packages is installed
  assert:
    that: item.value | length == 1
  loop: "{{ _cve_2023_41814_installed_pkgs | dict2items }}"

- name: Ensure major version of installed Slurm matches upgrade
  assert:
    that: _slurm_installed_major_ver == ['22', '05']
    fail_msg: "{{ item.key }} has major version {{ _slurm_installed_major_ver | join('.') }}, expecting 22.05"
  loop: "{{ _cve_2023_41814_installed_pkgs | dict2items }}"
  when: item.key.startswith('slurm')
  vars:
    _slurm_installed_major_ver: "{{ item.value[0].version.split('.')[0:2] }}"

